//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCTempl.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credenziali", Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
    [System.SerializableAttribute()]
    public partial class Credenziali : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RuoloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruolo {
            get {
                return this.RuoloField;
            }
            set {
                if ((object.ReferenceEquals(this.RuoloField, value) != true)) {
                    this.RuoloField = value;
                    this.RaisePropertyChanged("Ruolo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccount", Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
    [System.SerializableAttribute()]
    public partial class UserAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CognomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountRole {
            get {
                return this.AccountRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountRoleField, value) != true)) {
                    this.AccountRoleField = value;
                    this.RaisePropertyChanged("AccountRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cognome {
            get {
                return this.CognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.CognomeField, value) != true)) {
                    this.CognomeField = value;
                    this.RaisePropertyChanged("Cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CognomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNascitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cognome {
            get {
                return this.CognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.CognomeField, value) != true)) {
                    this.CognomeField = value;
                    this.RaisePropertyChanged("Cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascita {
            get {
                return this.DataNascitaField;
            }
            set {
                if ((this.DataNascitaField.Equals(value) != true)) {
                    this.DataNascitaField = value;
                    this.RaisePropertyChanged("DataNascita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Noleggio", Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
    [System.SerializableAttribute()]
    public partial class Noleggio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMVCTempl.ServiceReference1.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMVCTempl.ServiceReference1.DettaglioNoleggio[] ElencoDettagliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InizioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebMVCTempl.ServiceReference1.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebMVCTempl.ServiceReference1.DettaglioNoleggio[] ElencoDettagli {
            get {
                return this.ElencoDettagliField;
            }
            set {
                if ((object.ReferenceEquals(this.ElencoDettagliField, value) != true)) {
                    this.ElencoDettagliField = value;
                    this.RaisePropertyChanged("ElencoDettagli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fine {
            get {
                return this.FineField;
            }
            set {
                if ((this.FineField.Equals(value) != true)) {
                    this.FineField = value;
                    this.RaisePropertyChanged("Fine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Inizio {
            get {
                return this.InizioField;
            }
            set {
                if ((this.InizioField.Equals(value) != true)) {
                    this.InizioField = value;
                    this.RaisePropertyChanged("Inizio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DettaglioNoleggio", Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
    [System.SerializableAttribute()]
    public partial class DettaglioNoleggio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMVCTempl.ServiceReference1.Attrezzatura AttrezzaturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CostoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAttrezzaturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InizioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UtilizzatoriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebMVCTempl.ServiceReference1.Attrezzatura Attrezzatura {
            get {
                return this.AttrezzaturaField;
            }
            set {
                if ((object.ReferenceEquals(this.AttrezzaturaField, value) != true)) {
                    this.AttrezzaturaField = value;
                    this.RaisePropertyChanged("Attrezzatura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Costo {
            get {
                return this.CostoField;
            }
            set {
                if ((this.CostoField.Equals(value) != true)) {
                    this.CostoField = value;
                    this.RaisePropertyChanged("Costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fine {
            get {
                return this.FineField;
            }
            set {
                if ((this.FineField.Equals(value) != true)) {
                    this.FineField = value;
                    this.RaisePropertyChanged("Fine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAttrezzatura {
            get {
                return this.IdAttrezzaturaField;
            }
            set {
                if ((this.IdAttrezzaturaField.Equals(value) != true)) {
                    this.IdAttrezzaturaField = value;
                    this.RaisePropertyChanged("IdAttrezzatura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Inizio {
            get {
                return this.InizioField;
            }
            set {
                if ((this.InizioField.Equals(value) != true)) {
                    this.InizioField = value;
                    this.RaisePropertyChanged("Inizio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Utilizzatori {
            get {
                return this.UtilizzatoriField;
            }
            set {
                if ((this.UtilizzatoriField.Equals(value) != true)) {
                    this.UtilizzatoriField = value;
                    this.RaisePropertyChanged("Utilizzatori");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attrezzatura", Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
    [System.SerializableAttribute()]
    public partial class Attrezzatura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAttrezzaturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAttrezzatura {
            get {
                return this.IdAttrezzaturaField;
            }
            set {
                if ((this.IdAttrezzaturaField.Equals(value) != true)) {
                    this.IdAttrezzaturaField = value;
                    this.RaisePropertyChanged("IdAttrezzatura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Posti {
            get {
                return this.PostiField;
            }
            set {
                if ((this.PostiField.Equals(value) != true)) {
                    this.PostiField = value;
                    this.RaisePropertyChanged("Posti");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServices")]
    public interface IServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/Login", ReplyAction="http://tempuri.org/IServices/LoginResponse")]
        WebMVCTempl.ServiceReference1.Credenziali Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/Login", ReplyAction="http://tempuri.org/IServices/LoginResponse")]
        System.Threading.Tasks.Task<WebMVCTempl.ServiceReference1.Credenziali> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetUser", ReplyAction="http://tempuri.org/IServices/GetUserResponse")]
        WebMVCTempl.ServiceReference1.UserAccount GetUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetUser", ReplyAction="http://tempuri.org/IServices/GetUserResponse")]
        System.Threading.Tasks.Task<WebMVCTempl.ServiceReference1.UserAccount> GetUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/Register", ReplyAction="http://tempuri.org/IServices/RegisterResponse")]
        string Register(WebMVCTempl.ServiceReference1.Cliente c, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/Register", ReplyAction="http://tempuri.org/IServices/RegisterResponse")]
        System.Threading.Tasks.Task<string> RegisterAsync(WebMVCTempl.ServiceReference1.Cliente c, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/DeleteUser", ReplyAction="http://tempuri.org/IServices/DeleteUserResponse")]
        string DeleteUser(WebMVCTempl.ServiceReference1.UserAccount user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/DeleteUser", ReplyAction="http://tempuri.org/IServices/DeleteUserResponse")]
        System.Threading.Tasks.Task<string> DeleteUserAsync(WebMVCTempl.ServiceReference1.UserAccount user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getCliente", ReplyAction="http://tempuri.org/IServices/getClienteResponse")]
        WebMVCTempl.ServiceReference1.Cliente getCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getCliente", ReplyAction="http://tempuri.org/IServices/getClienteResponse")]
        System.Threading.Tasks.Task<WebMVCTempl.ServiceReference1.Cliente> getClienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/CancellaPrenotazione", ReplyAction="http://tempuri.org/IServices/CancellaPrenotazioneResponse")]
        string CancellaPrenotazione(int daEliminare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/CancellaPrenotazione", ReplyAction="http://tempuri.org/IServices/CancellaPrenotazioneResponse")]
        System.Threading.Tasks.Task<string> CancellaPrenotazioneAsync(int daEliminare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetPrenotazioni", ReplyAction="http://tempuri.org/IServices/GetPrenotazioniResponse")]
        WebMVCTempl.ServiceReference1.Noleggio[] GetPrenotazioni(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetPrenotazioni", ReplyAction="http://tempuri.org/IServices/GetPrenotazioniResponse")]
        System.Threading.Tasks.Task<WebMVCTempl.ServiceReference1.Noleggio[]> GetPrenotazioniAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicesChannel : WebMVCTempl.ServiceReference1.IServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesClient : System.ServiceModel.ClientBase<WebMVCTempl.ServiceReference1.IServices>, WebMVCTempl.ServiceReference1.IServices {
        
        public ServicesClient() {
        }
        
        public ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebMVCTempl.ServiceReference1.Credenziali Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<WebMVCTempl.ServiceReference1.Credenziali> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public WebMVCTempl.ServiceReference1.UserAccount GetUser(string username) {
            return base.Channel.GetUser(username);
        }
        
        public System.Threading.Tasks.Task<WebMVCTempl.ServiceReference1.UserAccount> GetUserAsync(string username) {
            return base.Channel.GetUserAsync(username);
        }
        
        public string Register(WebMVCTempl.ServiceReference1.Cliente c, string pw) {
            return base.Channel.Register(c, pw);
        }
        
        public System.Threading.Tasks.Task<string> RegisterAsync(WebMVCTempl.ServiceReference1.Cliente c, string pw) {
            return base.Channel.RegisterAsync(c, pw);
        }
        
        public string DeleteUser(WebMVCTempl.ServiceReference1.UserAccount user) {
            return base.Channel.DeleteUser(user);
        }
        
        public System.Threading.Tasks.Task<string> DeleteUserAsync(WebMVCTempl.ServiceReference1.UserAccount user) {
            return base.Channel.DeleteUserAsync(user);
        }
        
        public WebMVCTempl.ServiceReference1.Cliente getCliente() {
            return base.Channel.getCliente();
        }
        
        public System.Threading.Tasks.Task<WebMVCTempl.ServiceReference1.Cliente> getClienteAsync() {
            return base.Channel.getClienteAsync();
        }
        
        public string CancellaPrenotazione(int daEliminare) {
            return base.Channel.CancellaPrenotazione(daEliminare);
        }
        
        public System.Threading.Tasks.Task<string> CancellaPrenotazioneAsync(int daEliminare) {
            return base.Channel.CancellaPrenotazioneAsync(daEliminare);
        }
        
        public WebMVCTempl.ServiceReference1.Noleggio[] GetPrenotazioni(string username) {
            return base.Channel.GetPrenotazioni(username);
        }
        
        public System.Threading.Tasks.Task<WebMVCTempl.ServiceReference1.Noleggio[]> GetPrenotazioniAsync(string username) {
            return base.Channel.GetPrenotazioniAsync(username);
        }
    }
}
