//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCTempl.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credenziali", Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
    [System.SerializableAttribute()]
    public partial class Credenziali : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RuoloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruolo {
            get {
                return this.RuoloField;
            }
            set {
                if ((object.ReferenceEquals(this.RuoloField, value) != true)) {
                    this.RuoloField = value;
                    this.RaisePropertyChanged("Ruolo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccount", Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
    [System.SerializableAttribute()]
    public partial class UserAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CognomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountRole {
            get {
                return this.AccountRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountRoleField, value) != true)) {
                    this.AccountRoleField = value;
                    this.RaisePropertyChanged("AccountRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cognome {
            get {
                return this.CognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.CognomeField, value) != true)) {
                    this.CognomeField = value;
                    this.RaisePropertyChanged("Cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attrezzatura", Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
    [System.SerializableAttribute()]
    public partial class Attrezzatura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAttrezzaturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMVCTempl.ServiceReference1.CalendarioImpegni ImpegniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAttrezzatura {
            get {
                return this.IdAttrezzaturaField;
            }
            set {
                if ((this.IdAttrezzaturaField.Equals(value) != true)) {
                    this.IdAttrezzaturaField = value;
                    this.RaisePropertyChanged("IdAttrezzatura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebMVCTempl.ServiceReference1.CalendarioImpegni Impegni {
            get {
                return this.ImpegniField;
            }
            set {
                if ((object.ReferenceEquals(this.ImpegniField, value) != true)) {
                    this.ImpegniField = value;
                    this.RaisePropertyChanged("Impegni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Posti {
            get {
                return this.PostiField;
            }
            set {
                if ((this.PostiField.Equals(value) != true)) {
                    this.PostiField = value;
                    this.RaisePropertyChanged("Posti");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalendarioImpegni", Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
    [System.SerializableAttribute()]
    public partial class CalendarioImpegni : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMVCTempl.ServiceReference1.Impegno[] ImpegniField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_user {
            get {
                return this.Id_userField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_userField, value) != true)) {
                    this.Id_userField = value;
                    this.RaisePropertyChanged("Id_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebMVCTempl.ServiceReference1.Impegno[] Impegni {
            get {
                return this.ImpegniField;
            }
            set {
                if ((object.ReferenceEquals(this.ImpegniField, value) != true)) {
                    this.ImpegniField = value;
                    this.RaisePropertyChanged("Impegni");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Impegno", Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
    [System.SerializableAttribute()]
    public partial class Impegno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InizioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fine {
            get {
                return this.FineField;
            }
            set {
                if ((this.FineField.Equals(value) != true)) {
                    this.FineField = value;
                    this.RaisePropertyChanged("Fine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_user {
            get {
                return this.Id_userField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_userField, value) != true)) {
                    this.Id_userField = value;
                    this.RaisePropertyChanged("Id_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Inizio {
            get {
                return this.InizioField;
            }
            set {
                if ((this.InizioField.Equals(value) != true)) {
                    this.InizioField = value;
                    this.RaisePropertyChanged("Inizio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CognomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNascitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cognome {
            get {
                return this.CognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.CognomeField, value) != true)) {
                    this.CognomeField = value;
                    this.RaisePropertyChanged("Cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascita {
            get {
                return this.DataNascitaField;
            }
            set {
                if ((this.DataNascitaField.Equals(value) != true)) {
                    this.DataNascitaField = value;
                    this.RaisePropertyChanged("DataNascita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Noleggio", Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
    [System.SerializableAttribute()]
    public partial class Noleggio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMVCTempl.ServiceReference1.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMVCTempl.ServiceReference1.DettaglioNoleggio[] ElencoDettagliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InizioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebMVCTempl.ServiceReference1.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebMVCTempl.ServiceReference1.DettaglioNoleggio[] ElencoDettagli {
            get {
                return this.ElencoDettagliField;
            }
            set {
                if ((object.ReferenceEquals(this.ElencoDettagliField, value) != true)) {
                    this.ElencoDettagliField = value;
                    this.RaisePropertyChanged("ElencoDettagli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fine {
            get {
                return this.FineField;
            }
            set {
                if ((this.FineField.Equals(value) != true)) {
                    this.FineField = value;
                    this.RaisePropertyChanged("Fine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Inizio {
            get {
                return this.InizioField;
            }
            set {
                if ((this.InizioField.Equals(value) != true)) {
                    this.InizioField = value;
                    this.RaisePropertyChanged("Inizio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DettaglioNoleggio", Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
    [System.SerializableAttribute()]
    public partial class DettaglioNoleggio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMVCTempl.ServiceReference1.Attrezzatura AttrezzaturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CostoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAttrezzaturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InizioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UtilizzatoriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebMVCTempl.ServiceReference1.Attrezzatura Attrezzatura {
            get {
                return this.AttrezzaturaField;
            }
            set {
                if ((object.ReferenceEquals(this.AttrezzaturaField, value) != true)) {
                    this.AttrezzaturaField = value;
                    this.RaisePropertyChanged("Attrezzatura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Costo {
            get {
                return this.CostoField;
            }
            set {
                if ((this.CostoField.Equals(value) != true)) {
                    this.CostoField = value;
                    this.RaisePropertyChanged("Costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fine {
            get {
                return this.FineField;
            }
            set {
                if ((this.FineField.Equals(value) != true)) {
                    this.FineField = value;
                    this.RaisePropertyChanged("Fine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAttrezzatura {
            get {
                return this.IdAttrezzaturaField;
            }
            set {
                if ((this.IdAttrezzaturaField.Equals(value) != true)) {
                    this.IdAttrezzaturaField = value;
                    this.RaisePropertyChanged("IdAttrezzatura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Inizio {
            get {
                return this.InizioField;
            }
            set {
                if ((this.InizioField.Equals(value) != true)) {
                    this.InizioField = value;
                    this.RaisePropertyChanged("Inizio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Utilizzatori {
            get {
                return this.UtilizzatoriField;
            }
            set {
                if ((this.UtilizzatoriField.Equals(value) != true)) {
                    this.UtilizzatoriField = value;
                    this.RaisePropertyChanged("Utilizzatori");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lezione", Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
    [System.SerializableAttribute()]
    public partial class Lezione : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMVCTempl.ServiceReference1.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CostoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InizioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMVCTempl.ServiceReference1.Istruttore IstruttoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PartecipantiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebMVCTempl.ServiceReference1.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Costo {
            get {
                return this.CostoField;
            }
            set {
                if ((this.CostoField.Equals(value) != true)) {
                    this.CostoField = value;
                    this.RaisePropertyChanged("Costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fine {
            get {
                return this.FineField;
            }
            set {
                if ((this.FineField.Equals(value) != true)) {
                    this.FineField = value;
                    this.RaisePropertyChanged("Fine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Inizio {
            get {
                return this.InizioField;
            }
            set {
                if ((this.InizioField.Equals(value) != true)) {
                    this.InizioField = value;
                    this.RaisePropertyChanged("Inizio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebMVCTempl.ServiceReference1.Istruttore Istruttore {
            get {
                return this.IstruttoreField;
            }
            set {
                if ((object.ReferenceEquals(this.IstruttoreField, value) != true)) {
                    this.IstruttoreField = value;
                    this.RaisePropertyChanged("Istruttore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Partecipanti {
            get {
                return this.PartecipantiField;
            }
            set {
                if ((this.PartecipantiField.Equals(value) != true)) {
                    this.PartecipantiField = value;
                    this.RaisePropertyChanged("Partecipanti");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Istruttore", Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
    [System.SerializableAttribute()]
    public partial class Istruttore : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttivitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CognomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNascitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IbanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMVCTempl.ServiceReference1.CalendarioImpegni ImpegniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Attivita {
            get {
                return this.AttivitaField;
            }
            set {
                if ((object.ReferenceEquals(this.AttivitaField, value) != true)) {
                    this.AttivitaField = value;
                    this.RaisePropertyChanged("Attivita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cognome {
            get {
                return this.CognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.CognomeField, value) != true)) {
                    this.CognomeField = value;
                    this.RaisePropertyChanged("Cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascita {
            get {
                return this.DataNascitaField;
            }
            set {
                if ((this.DataNascitaField.Equals(value) != true)) {
                    this.DataNascitaField = value;
                    this.RaisePropertyChanged("DataNascita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Iban {
            get {
                return this.IbanField;
            }
            set {
                if ((object.ReferenceEquals(this.IbanField, value) != true)) {
                    this.IbanField = value;
                    this.RaisePropertyChanged("Iban");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebMVCTempl.ServiceReference1.CalendarioImpegni Impegni {
            get {
                return this.ImpegniField;
            }
            set {
                if ((object.ReferenceEquals(this.ImpegniField, value) != true)) {
                    this.ImpegniField = value;
                    this.RaisePropertyChanged("Impegni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Orario {
            get {
                return this.OrarioField;
            }
            set {
                if ((object.ReferenceEquals(this.OrarioField, value) != true)) {
                    this.OrarioField = value;
                    this.RaisePropertyChanged("Orario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lezione", Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
    [System.SerializableAttribute()]
    public partial class Lezione : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMVCTempl.ServiceReference1.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CostoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InizioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMVCTempl.ServiceReference1.Istruttore IstruttoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PartecipantiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebMVCTempl.ServiceReference1.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Costo {
            get {
                return this.CostoField;
            }
            set {
                if ((this.CostoField.Equals(value) != true)) {
                    this.CostoField = value;
                    this.RaisePropertyChanged("Costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fine {
            get {
                return this.FineField;
            }
            set {
                if ((this.FineField.Equals(value) != true)) {
                    this.FineField = value;
                    this.RaisePropertyChanged("Fine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Inizio {
            get {
                return this.InizioField;
            }
            set {
                if ((this.InizioField.Equals(value) != true)) {
                    this.InizioField = value;
                    this.RaisePropertyChanged("Inizio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebMVCTempl.ServiceReference1.Istruttore Istruttore {
            get {
                return this.IstruttoreField;
            }
            set {
                if ((object.ReferenceEquals(this.IstruttoreField, value) != true)) {
                    this.IstruttoreField = value;
                    this.RaisePropertyChanged("Istruttore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Partecipanti {
            get {
                return this.PartecipantiField;
            }
            set {
                if ((this.PartecipantiField.Equals(value) != true)) {
                    this.PartecipantiField = value;
                    this.RaisePropertyChanged("Partecipanti");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Istruttore", Namespace="http://schemas.datacontract.org/2004/07/WCFWebService.Model")]
    [System.SerializableAttribute()]
    public partial class Istruttore : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttivitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CognomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNascitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IbanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMVCTempl.ServiceReference1.CalendarioImpegni ImpegniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Attivita {
            get {
                return this.AttivitaField;
            }
            set {
                if ((object.ReferenceEquals(this.AttivitaField, value) != true)) {
                    this.AttivitaField = value;
                    this.RaisePropertyChanged("Attivita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cognome {
            get {
                return this.CognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.CognomeField, value) != true)) {
                    this.CognomeField = value;
                    this.RaisePropertyChanged("Cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascita {
            get {
                return this.DataNascitaField;
            }
            set {
                if ((this.DataNascitaField.Equals(value) != true)) {
                    this.DataNascitaField = value;
                    this.RaisePropertyChanged("DataNascita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Iban {
            get {
                return this.IbanField;
            }
            set {
                if ((object.ReferenceEquals(this.IbanField, value) != true)) {
                    this.IbanField = value;
                    this.RaisePropertyChanged("Iban");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebMVCTempl.ServiceReference1.CalendarioImpegni Impegni {
            get {
                return this.ImpegniField;
            }
            set {
                if ((object.ReferenceEquals(this.ImpegniField, value) != true)) {
                    this.ImpegniField = value;
                    this.RaisePropertyChanged("Impegni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Orario {
            get {
                return this.OrarioField;
            }
            set {
                if ((object.ReferenceEquals(this.OrarioField, value) != true)) {
                    this.OrarioField = value;
                    this.RaisePropertyChanged("Orario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServices")]
    public interface IServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/Login", ReplyAction="http://tempuri.org/IServices/LoginResponse")]
        WebMVCTempl.ServiceReference1.Credenziali Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/Login", ReplyAction="http://tempuri.org/IServices/LoginResponse")]
        System.Threading.Tasks.Task<WebMVCTempl.ServiceReference1.Credenziali> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetUser", ReplyAction="http://tempuri.org/IServices/GetUserResponse")]
        WebMVCTempl.ServiceReference1.UserAccount GetUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetUser", ReplyAction="http://tempuri.org/IServices/GetUserResponse")]
        System.Threading.Tasks.Task<WebMVCTempl.ServiceReference1.UserAccount> GetUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetAttrezzatura", ReplyAction="http://tempuri.org/IServices/GetAttrezzaturaResponse")]
        WebMVCTempl.ServiceReference1.Attrezzatura[] GetAttrezzatura();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetAttrezzatura", ReplyAction="http://tempuri.org/IServices/GetAttrezzaturaResponse")]
        System.Threading.Tasks.Task<WebMVCTempl.ServiceReference1.Attrezzatura[]> GetAttrezzaturaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/AggiornaAttrezzatura", ReplyAction="http://tempuri.org/IServices/AggiornaAttrezzaturaResponse")]
        bool AggiornaAttrezzatura(WebMVCTempl.ServiceReference1.Attrezzatura a, int quantita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/AggiornaAttrezzatura", ReplyAction="http://tempuri.org/IServices/AggiornaAttrezzaturaResponse")]
        System.Threading.Tasks.Task<bool> AggiornaAttrezzaturaAsync(WebMVCTempl.ServiceReference1.Attrezzatura a, int quantita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/Register", ReplyAction="http://tempuri.org/IServices/RegisterResponse")]
        string Register(WebMVCTempl.ServiceReference1.Cliente c, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/Register", ReplyAction="http://tempuri.org/IServices/RegisterResponse")]
        System.Threading.Tasks.Task<string> RegisterAsync(WebMVCTempl.ServiceReference1.Cliente c, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/DisponibilitaAttrezzatura", ReplyAction="http://tempuri.org/IServices/DisponibilitaAttrezzaturaResponse")]
        int[][] DisponibilitaAttrezzatura(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/DisponibilitaAttrezzatura", ReplyAction="http://tempuri.org/IServices/DisponibilitaAttrezzaturaResponse")]
        System.Threading.Tasks.Task<int[][]> DisponibilitaAttrezzaturaAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/CreaNoleggio", ReplyAction="http://tempuri.org/IServices/CreaNoleggioResponse")]
        string CreaNoleggio(string user, System.DateTime inizio, System.DateTime fine, string[] attr, int[] pers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/CreaNoleggio", ReplyAction="http://tempuri.org/IServices/CreaNoleggioResponse")]
        System.Threading.Tasks.Task<string> CreaNoleggioAsync(string user, System.DateTime inizio, System.DateTime fine, string[] attr, int[] pers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/CancellaPrenotazione", ReplyAction="http://tempuri.org/IServices/CancellaPrenotazioneResponse")]
        string CancellaPrenotazione(int daEliminare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/CancellaPrenotazione", ReplyAction="http://tempuri.org/IServices/CancellaPrenotazioneResponse")]
        System.Threading.Tasks.Task<string> CancellaPrenotazioneAsync(int daEliminare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetPrenotazioni", ReplyAction="http://tempuri.org/IServices/GetPrenotazioniResponse")]
        WebMVCTempl.ServiceReference1.Noleggio[] GetPrenotazioni(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetPrenotazioni", ReplyAction="http://tempuri.org/IServices/GetPrenotazioniResponse")]
        System.Threading.Tasks.Task<WebMVCTempl.ServiceReference1.Noleggio[]> GetPrenotazioniAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetLezioni", ReplyAction="http://tempuri.org/IServices/GetLezioniResponse")]
        string[][] GetLezioni(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetLezioni", ReplyAction="http://tempuri.org/IServices/GetLezioniResponse")]
        System.Threading.Tasks.Task<string[][]> GetLezioniAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetListLezioni", ReplyAction="http://tempuri.org/IServices/GetListLezioniResponse")]
        WebMVCTempl.ServiceReference1.Lezione[] GetListLezioni(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetListLezioni", ReplyAction="http://tempuri.org/IServices/GetListLezioniResponse")]
        System.Threading.Tasks.Task<WebMVCTempl.ServiceReference1.Lezione[]> GetListLezioniAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/DisponibilitaIstruttori", ReplyAction="http://tempuri.org/IServices/DisponibilitaIstruttoriResponse")]
        string[][] DisponibilitaIstruttori(System.DateTime date, string attivita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/DisponibilitaIstruttori", ReplyAction="http://tempuri.org/IServices/DisponibilitaIstruttoriResponse")]
        System.Threading.Tasks.Task<string[][]> DisponibilitaIstruttoriAsync(System.DateTime date, string attivita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetCliente", ReplyAction="http://tempuri.org/IServices/GetClienteResponse")]
        WebMVCTempl.ServiceReference1.Cliente GetCliente(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetCliente", ReplyAction="http://tempuri.org/IServices/GetClienteResponse")]
        System.Threading.Tasks.Task<WebMVCTempl.ServiceReference1.Cliente> GetClienteAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/CreaLezione", ReplyAction="http://tempuri.org/IServices/CreaLezioneResponse")]
        string CreaLezione(string username, System.DateTime inizio, System.DateTime fine, string istr, int persone, string attivita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/CreaLezione", ReplyAction="http://tempuri.org/IServices/CreaLezioneResponse")]
        System.Threading.Tasks.Task<string> CreaLezioneAsync(string username, System.DateTime inizio, System.DateTime fine, string istr, int persone, string attivita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/DeleteUser", ReplyAction="http://tempuri.org/IServices/DeleteUserResponse")]
        string DeleteUser(WebMVCTempl.ServiceReference1.UserAccount user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/DeleteUser", ReplyAction="http://tempuri.org/IServices/DeleteUserResponse")]
        System.Threading.Tasks.Task<string> DeleteUserAsync(WebMVCTempl.ServiceReference1.UserAccount user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetString", ReplyAction="http://tempuri.org/IServices/GetStringResponse")]
        string GetString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetString", ReplyAction="http://tempuri.org/IServices/GetStringResponse")]
        System.Threading.Tasks.Task<string> GetStringAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicesChannel : WebMVCTempl.ServiceReference1.IServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesClient : System.ServiceModel.ClientBase<WebMVCTempl.ServiceReference1.IServices>, WebMVCTempl.ServiceReference1.IServices {
        
        public ServicesClient() {
        }
        
        public ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebMVCTempl.ServiceReference1.Credenziali Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<WebMVCTempl.ServiceReference1.Credenziali> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public WebMVCTempl.ServiceReference1.UserAccount GetUser(string username) {
            return base.Channel.GetUser(username);
        }
        
        public System.Threading.Tasks.Task<WebMVCTempl.ServiceReference1.UserAccount> GetUserAsync(string username) {
            return base.Channel.GetUserAsync(username);
        }
        
        public WebMVCTempl.ServiceReference1.Attrezzatura[] GetAttrezzatura() {
            return base.Channel.GetAttrezzatura();
        }
        
        public System.Threading.Tasks.Task<WebMVCTempl.ServiceReference1.Attrezzatura[]> GetAttrezzaturaAsync() {
            return base.Channel.GetAttrezzaturaAsync();
        }
        
        public bool AggiornaAttrezzatura(WebMVCTempl.ServiceReference1.Attrezzatura a, int quantita) {
            return base.Channel.AggiornaAttrezzatura(a, quantita);
        }
        
        public System.Threading.Tasks.Task<bool> AggiornaAttrezzaturaAsync(WebMVCTempl.ServiceReference1.Attrezzatura a, int quantita) {
            return base.Channel.AggiornaAttrezzaturaAsync(a, quantita);
        }
        
        public string Register(WebMVCTempl.ServiceReference1.Cliente c, string pw) {
            return base.Channel.Register(c, pw);
        }
        
        public System.Threading.Tasks.Task<string> RegisterAsync(WebMVCTempl.ServiceReference1.Cliente c, string pw) {
            return base.Channel.RegisterAsync(c, pw);
        }
        
        public int[][] DisponibilitaAttrezzatura(System.DateTime date) {
            return base.Channel.DisponibilitaAttrezzatura(date);
        }
        
        public System.Threading.Tasks.Task<int[][]> DisponibilitaAttrezzaturaAsync(System.DateTime date) {
            return base.Channel.DisponibilitaAttrezzaturaAsync(date);
        }
        
        public string CreaNoleggio(string user, System.DateTime inizio, System.DateTime fine, string[] attr, int[] pers) {
            return base.Channel.CreaNoleggio(user, inizio, fine, attr, pers);
        }
        
        public System.Threading.Tasks.Task<string> CreaNoleggioAsync(string user, System.DateTime inizio, System.DateTime fine, string[] attr, int[] pers) {
            return base.Channel.CreaNoleggioAsync(user, inizio, fine, attr, pers);
        }
        
        public string CancellaPrenotazione(int daEliminare) {
            return base.Channel.CancellaPrenotazione(daEliminare);
        }
        
        public System.Threading.Tasks.Task<string> CancellaPrenotazioneAsync(int daEliminare) {
            return base.Channel.CancellaPrenotazioneAsync(daEliminare);
        }
        
        public WebMVCTempl.ServiceReference1.Noleggio[] GetPrenotazioni(string username) {
            return base.Channel.GetPrenotazioni(username);
        }
        
        public System.Threading.Tasks.Task<WebMVCTempl.ServiceReference1.Noleggio[]> GetPrenotazioniAsync(string username) {
            return base.Channel.GetPrenotazioniAsync(username);
        }
        
        public string[][] GetLezioni(string username) {
            return base.Channel.GetLezioni(username);
        }
        
        public System.Threading.Tasks.Task<string[][]> GetLezioniAsync(string username) {
            return base.Channel.GetLezioniAsync(username);
        }
        
        public WebMVCTempl.ServiceReference1.Lezione[] GetListLezioni(string username) {
            return base.Channel.GetListLezioni(username);
        }
        
        public System.Threading.Tasks.Task<WebMVCTempl.ServiceReference1.Lezione[]> GetListLezioniAsync(string username) {
            return base.Channel.GetListLezioniAsync(username);
        }
        
        public string[][] DisponibilitaIstruttori(System.DateTime date, string attivita) {
            return base.Channel.DisponibilitaIstruttori(date, attivita);
        }
        
        public System.Threading.Tasks.Task<string[][]> DisponibilitaIstruttoriAsync(System.DateTime date, string attivita) {
            return base.Channel.DisponibilitaIstruttoriAsync(date, attivita);
        }
        
        public WebMVCTempl.ServiceReference1.Cliente GetCliente(string username) {
            return base.Channel.GetCliente(username);
        }
        
        public System.Threading.Tasks.Task<WebMVCTempl.ServiceReference1.Cliente> GetClienteAsync(string username) {
            return base.Channel.GetClienteAsync(username);
        }
        
        public string CreaLezione(string username, System.DateTime inizio, System.DateTime fine, string istr, int persone, string attivita) {
            return base.Channel.CreaLezione(username, inizio, fine, istr, persone, attivita);
        }
        
        public System.Threading.Tasks.Task<string> CreaLezioneAsync(string username, System.DateTime inizio, System.DateTime fine, string istr, int persone, string attivita) {
            return base.Channel.CreaLezioneAsync(username, inizio, fine, istr, persone, attivita);
        }
        
        public string DeleteUser(WebMVCTempl.ServiceReference1.UserAccount user) {
            return base.Channel.DeleteUser(user);
        }
        
        public System.Threading.Tasks.Task<string> DeleteUserAsync(WebMVCTempl.ServiceReference1.UserAccount user) {
            return base.Channel.DeleteUserAsync(user);
        }
        
        public string GetString() {
            return base.Channel.GetString();
        }
        
        public System.Threading.Tasks.Task<string> GetStringAsync() {
            return base.Channel.GetStringAsync();
        }
    }
}
